# -*- coding: utf-8 -*-
"""funcCalcUser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jXFwBghsyQAgcdcmH-hFZwuK5b9dpv1s
"""

def calculadora():
    while True:
        print("\n1: Soma")
        print("2: Subtração")
        print("3: Multiplicação")
        print("4: Divisão")
        print("0: Sair")

        escolha = input("Digite o número para a operação desejada: ")

        if escolha == '0':
            print("Calculadora encerrada.")
            break
        elif escolha in {'1', '2', '3', '4'}:
            num1 = float(input("Digite o primeiro valor: "))
            num2 = float(input("Digite o segundo valor: "))

            if escolha == '1':
                resultado = num1 + num2
                print("Resultado:", resultado)
            elif escolha == '2':
                resultado = num1 - num2
                print("Resultado:", resultado)
            elif escolha == '3':
                resultado = num1 * num2
                print("Resultado:", resultado)
            elif escolha == '4':
                if num2 != 0:
                    resultado = num1 / num2
                    print("Resultado:", resultado)
                else:
                    print("Erro: divisão por zero!")
        else:
            print("Essa opção não existe. Digite uma opção válida.")

calculadora()