# -*- coding: utf-8 -*-
"""progIdade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yvl1LOMJCCmtLvRetIydevbP-NZykkHP
"""

import datetime

def calc_ano_nasc():
    while True:
        try:
            ano = int(input("Digite seu ano de nascimento: "))
            if 1922 <= ano <= 2021:
                return ano
            else:
                print("Ano não permitido.")
        except ValueError:
            print("Por favor, digite um ano válido.")

def calc_idade(ano_nasc):
    ano_atual = datetime.datetime.now().year
    return ano_atual - ano_nasc

def aniversario():
    nome = input("Digite seu nome completo: ")
    ano_nasc = calc_ano_nasc()
    idade = calc_idade(ano_nasc)
    print(f"Olá, {nome}! Você completou (ou completará) {idade} anos em 2024.")

if __name__ == "__main__":
    aniversario()