# -*- coding: utf-8 -*-
"""projeto-hotel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tGikG41w0VcLMlCfHX1vVRJWJhH2f8jc
"""

for i in range(20, 0, -1):
  if (i == 13):
    continue
  print (i)

i = 20
while (i >= 1):
  if (i != 13):
    print (i)
  i = i - 1